module.exports = [
   "Acting",
   "Air Sports",
   "Aircraft Spotting",
   "Airsoft",
   "Algorithms",
   "Amateur Radio",
   "American Football",
   "American Football Portal",
   "Animal Fancy",
   "Antiquing",
   "Antiquities",
   "Aqua-lun",
   "Archery",
   "Archery",
   "Art Collecting",
   "Association Football",
   "Association Football Portal",
   "Astrology",
   "Astronomy",
   "Audiophilia",
   "Australian Rules Football",
   "Auto Audiophilia",
   "Auto Racing",
   "Backpacking",
   "Badminton",
   "Badminton Portal",
   "Base Jumping",
   "Baseball",
   "Baseball",
   "Baseball Portal",
   "Basketball",
   "Basketball Portal",
   "Baton Twirling",
   "Baton Twirling",
   "Beach Volleyball",
   "Beekeeping",
   "Billiards",
   "Bird Watching",
   "Birdwatching",
   "Blacksmithin",
   "Board Games",
   "Board Sports",
   "Bodybuilding",
   "Book Collecting",
   "Book Reports",
   "Bowling",
   "Boxing",
   "Brazilian Jiu-jitsu",
   "Breakdancing",
   "Bridge",
   "Buildings",
   "Bus Spotting",
   "Calligraphy",
   "Candle Making",
   "Card Collecting",
   "Cheerleading",
   "Chess",
   "Chess Portal",
   "Climbing",
   "Coin Collecting",
   "College Football Portal",
   "Color Guard",
   "Coloring",
   "Comic Book Collecting",
   "Computer Programming",
   "Cooking",
   "Cosplaying",
   "Couponing",
   "Coursework",
   "Creative Writing",
   "Cricket",
   "Cricket Portal",
   "Crocheting",
   "Cryptography",
   "Curling",
   "Cycling",
   "Cycling",
   "Cycling Portal",
   "Dance",
   "Dancing",
   "Darts",
   "Debate",
   "Debate",
   "Deltiology (Postcard Collecting)",
   "Designs",
   "Digital Arts",
   "Disc Golf",
   "Dog Sport",
   "Dowsing",
   "Drama",
   "Drawing",
   "Drawings",
   "Driving",
   "Electronics",
   "Element Collecting",
   "Embroidery ",
   "Equestrianism",
   "Essays",
   "Exams",
   "Exhibition Drill",
   "Fencing",
   "Field Hockey",
   "Figure Skating",
   "Figure Skating Portal",
   "Fishing",
   "Fishing",
   "Fishing Portal",
   "Fishkeeping",
   "Flag Football",
   "Flower Arranging",
   "Flower Collecting And Pressing",
   "Flying",
   "Footbag",
   "Foraging",
   "Foreign Language Learning",
   "Formula One Portal",
   "Fossil Hunting",
   "Gambling",
   "Gaming (Tabletop Games And Role-playing Games)",
   "Gardening",
   "Genealogy",
   "Geocaching",
   "Geocaching",
   "Geology",
   "Ghost Hunting",
   "Glassblowing",
   "Go",
   "Golf Portal",
   "Golfing",
   "Gongoozling",
   "Graffiti",
   "Gunsmithin",
   "Gymnastics",
   "Gymnastics Portal",
   "Handball",
   "Handball",
   "Herping",
   "Hiking",
   "Homebrewing",
   "Homework",
   "Hooping",
   "Hunting",
   "Ice Hockey",
   "Ice Hockey Portal",
   "Ice Skating",
   "Inline Skating",
   "Insect Collecting",
   "Jewelry Making",
   "Jigsaw Puzzles",
   "Job Training",
   "Jogging",
   "Judo",
   "Juggling",
   "Jukskei",
   "Kabaddi",
   "Kart Racing",
   "Kayaking",
   "Kite Flying",
   "Kitesurfing",
   "Knappin",
   "Knife Makin",
   "Knife Throwin",
   "Knitting",
   "Lab",
   "Laboratory",
   "Lacemaking",
   "Lapidary",
   "Larping",
   "Laser Tag",
   "Leather Crafting",
   "Lego Building",
   "Letterboxing",
   "Listening To Music",
   "Machining",
   "Macrame",
   "Magic",
   "Mahjong",
   "Marbles",
   "Martial Arts",
   "Math Problems",
   "Metal Detecting",
   "Metal Detecting",
   "Meteorology",
   "Microscopy",
   "Mineral Collecting",
   "Model Aircraft",
   "Model Building",
   "Motor Sports",
   "Mountain Biking",
   "Mountaineering",
   "Movie And Movie Memorabilia Collecting",
   "Multiple Choice Tests",
   "Mushroom Hunting/mycology",
   "Netball",
   "Nordic Skating",
   "Online Homework",
   "Orienteering",
   "Origami",
   "Paintball",
   "Painting",
   "Papers",
   "Parkour",
   "People Watching",
   "Performance",
   "Photography",
   "Physical Training",
   "Pigeon Racing",
   "Playing Musical Instruments",
   "Poker",
   "Polo",
   "Posters",
   "Pottery",
   "Problem Sets",
   "Programming Assignments",
   "Projects",
   "Puzzles",
   "Quilting",
   "Quizzes",
   "Quizzes",
   "Racquetball",
   "Radio-controlled Car Racing",
   "Rafting",
   "Rappelling",
   "Reading",
   "Reading",
   "Record Collecting",
   "Research Paper",
   "Rock Balancing",
   "Rock Climbing",
   "Roller Derby",
   "Roller Skating",
   "Rugby",
   "Rugby League Football",
   "Rugby League Portal",
   "Rugby Union Portal",
   "Running",
   "Sailing",
   "Sand Art",
   "Schoolwork",
   "Scrapbooking",
   "Scuba Diving",
   "Sculling Or Rowing",
   "Sculpting",
   "Sea Glass Collecting",
   "Seashell Collecting",
   "Sewing",
   "Shooting",
   "Shooting Sport",
   "Shopping",
   "Shortwave Listening",
   "Singing",
   "Skateboarding",
   "Skateboarding",
   "Sketching",
   "Skiing",
   "Skimboarding",
   "Skydiving",
   "Slacklining",
   "Slot Car Racing",
   "Snooker Portal",
   "Snowboarding",
   "Soapmaking",
   "Speeches",
   "Speed Skating",
   "Sports",
   "Sports And Games Portal",
   "Squash",
   "Stamp Collecting",
   "Stand-up Comedy",
   "Stone Collecting",
   "Stone Skipping",
   "Strategy Games Portal",
   "Studio",
   "Sudoku",
   "Surfing",
   "Surfing",
   "Swimming",
   "Swimming",
   "Swimming Portal",
   "Table Football",
   "Table Tennis",
   "Table Tennis",
   "Taekwondo",
   "Tai Chi",
   "Taxidermy",
   "Technical Papers",
   "Tennis",
   "Tennis Portal",
   "Tests",
   "Timed Tests",
   "Tour Skating",
   "Trainspotting",
   "Traveling",
   "Triathlon",
   "Ultimate Frisbee ",
   "Urban Exploration",
   "Vehicle Restoration",
   "Video Game Collecting",
   "Video Games",
   "Video Games Portal",
   "Video Gaming",
   "Videophilia",
   "Vintage Cars",
   "Volleyball",
   "Volleyball",
   "Watching Movies",
   "Water Sports",
   "Web Surfing",
   "Weightlifting",
   "Wood Carving",
   "Woodworking",
   "Worldbuilding",
   "Writing",
   "Written Tests",
   "Yo-yoing",
   "Yoga"
];