/**
 * A list of all undergraduate majors at calpoly.
 * @author Michael Murphy
 * @type {string[]}
 */
module.exports = [
   "Aerospace Engineering",
   "Agricultural and Environmental Plant Sciences",
   "Agricultural Business",
   "Agricultural Communication",
   "Agricultural Science",
   "Agricultural Systems Management",
   "Animal Science",
   "Anthropology and Geography",
   "Architectural Engineering",
   "Architecture",
   "Art and Design",
   "Biochemistry",
   "Biological Sciences",
   "Biomedical Engineering",
   "BioResource and Agricultural Engineering",
   "Business Administration",
   "Chemistry",
   "Child Development",
   "City and Regional Planning",
   "Civil Engineering",
   "Communication Studies",
   "Comparative Ethnic Studies",
   "Computer Engineering",
   "Computer Science",
   "Construction Management",
   "Dairy Science",
   "Earth Science",
   "Economics",
   "Electrical Engineering",
   "English",
   "Environmental Earth and Soil Sciences",
   "Environmental Earth Science",
   "Environmental Engineering",
   "Environmental Management and Protection",
   "Environmental Soil Science",
   "Food Science",
   "Forestry and Natural Resources",
   "General Engineering",
   "Graphic Communication",
   "History",
   "Industrial Engineering",
   "Industrial Technology",
   "Industrial Technology and Packaging",
   "Journalism",
   "Kinesiology",
   "Landscape Architecture",
   "Liberal Arts and Engineering Studies",
   "Liberal Studies",
   "Manufacturing Engineering",
   "Materials Engineering",
   "Mathematics",
   "Mechanical Engineering",
   "Microbiology",
   "Modern Languages and Literatures",
   "Music",
   "Nutrition",
   "Philosophy",
   "Physics",
   "Political Science",
   "Psychology",
   "Recreation, Parks, and Tourism Administration",
   "Sociology",
   "Software Engineering",
   "Soil Science",
   "Statistics",
   "Theatre Arts",
   "Wine and Viticulture"
];